### ISSUE TITLE
Question about "kp" in "cur_data" and "ref_data"

### ISSUE THREAD

**Issue by Beniko95J** [Huangying-Zhan/DF-VO#11]
Hi, I am trying to understand your code and have a question about the meaning of some statements in vo_modules.py:

        cur_data['kp_best'] = batch_kp_ref_best[0].copy() # cur_data save each kp at ref-view (i.e. regular grid)
        cur_data['kp_list'] = batch_kp_ref_regular[0].copy() # cur_data save each kp at ref-view (i.e. regular grid)
        cur_data['kp_best'] = cur_data['kp_best'][cur_data['kp_best'][:,0]!=-1] # remove invalid kp

Why should the "kp" in reference frame be assigned to current frame?

Thank you!

**Comment by Huangying-Zhan** [comment]
Please see this issue. #7
