### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by saimouli** [Huangying-Zhan/DF-VO#12]
Are the depth and flow training codes released? I can see inference scripts and weights, but could not find training code. 

I have been to the referenced repositories, but I believe there were slight changes you have done to achieve the results?

To be sure, from depth (mono) estimation network will predict the pose of the camera and the depth?

**Comment by Huangying-Zhan** [comment]
Unfortunately, I still don't have a plan to clean the training part. 
However, you can find all the related losses/operations in our latest online-finetuning modules.

https://github.com/Huangying-Zhan/DF-VO/blob/master/libs/deep_models/flow/deep_flow.py

https://github.com/Huangying-Zhan/DF-VO/tree/master/libs/deep_models
