### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by nankeqin** [Huangying-Zhan/DF-VO#17]
Thank you for sharing the evaluation code and pretrained models. But I can not find training code. Do you plan to release the training source code in the near future?

**Comment by Huangying-Zhan** [comment]
Sorry, I still don't have a plan to clean the training part. However, you can find all the related losses/operations in our online-finetuning modules. 

https://github.com/Huangying-Zhan/DF-VO/blob/master/libs/deep_models/flow/deep_flow.py

https://github.com/Huangying-Zhan/DF-VO/tree/master/libs/deep_models
