### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by genius-hl** [Huangying-Zhan/DF-VO#19]
Hello,when I  execute the following command:
`python apis/run.py -d options/examples/default_configuration.yml`
The terminal  print this message：
`Save result in result/tmp/0/? [y/n]y `
`==> Initialize LiteFlowNet with [model_zoo/optical_flow/LiteFlowNet/network-default.pytorch]:`
`==> Initialize Depth-CNN with [model_zoo/depth/kitti_odom/stereo/]
`
`==> Start DF-VO
`
`==> Running sequence: 10
`
`Start with frame: 25
`
`0it [00:00, ?it/s]
`
`=> Finish!
`
`The result is saved in [result/tmp/0/].
`
`Save VO map.
`
`Trajectory saved.
`
`----- time breakdown -----
`
`Group [single]:`
But the map.png in the result folder is black and .txt file only save one line of data.Is the dataset not imported and run?
Thank you for your help!

**Comment by Huangying-Zhan** [comment]
Hi genius-hl, could you check the data directory/data loading to make sure if the images have been loaded?

**Comment by songwenhuang** [comment]
Got the same error. Any solution for this?

**Comment by Huangying-Zhan** [comment]
Yes, because I have converted KITTI data from png to jpg. Please update `image: ext` in the configuration file.

**Comment by genius-hl** [comment]
> Got the same error. The issue was fixed after changing "jpg" to "png."
Thank you for your tips !

**Comment by genius-hl** [comment]
> Got the same error. The issue was fixed after changing "jpg" to "png."

Thank you for yout tips!

**Comment by genius-hl** [comment]
> Yes, because I have converted KITTI data from png to jpg. Please update `image: ext` in the configuration file.

Thank you for your reply ! I got the result.
