### ISSUE TITLE
KeyError: 'motion' in dfvo.py

### ISSUE THREAD

**Issue by songwenhuang** [Huangying-Zhan/DF-VO#20]
After running python run.py -d options/examples/default_configuration.yml

Got the following error message in the terminal:

KeyError: 'motion' in dfvo.py.

Any solution for this?

============================================================================

Save result in result/tmp/10/? [y/n]y
==> Initialize LiteFlowNet with [model_zoo/optical_flow/LiteFlowNet/network-default.pytorch]: 
==> Initialize Depth-CNN with [model_zoo/depth/kitti_odom/stereo/]
==> Start DF-VO
==> Running sequence: 10
Start with frame: 1
  0%|                                          | 1/1200 [00:00<12:50,  1.56it/s]/home/user/.local/lib/python3.6/site-packages/torch/nn/functional.py:3384: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Cannot find enough good keypoints!
No enough good keypoints, constant motion will be used!

Traceback (most recent call last):
  File "run.py", line 85, in <module>
    vo.main()
  File "/home/user/workspace/DF-VO/libs/dfvo.py", line 382, in main
    self.tracking()
  File "/home/user/workspace/DF-VO/libs/dfvo.py", line 162, in tracking
    pose = self.ref_data['motion']
    
KeyError: 'motion'

**Comment by Huangying-Zhan** [comment]
@songwenhuang  are u running KITTI or other datasets?

**Comment by songwenhuang** [comment]
@Huangying-Zhan I am using KITTI Visual Odometry dataset.

**Comment by Huangying-Zhan** [comment]
"Cannot find enough good keypoints!" usually happens in extreme cases (e.g. under/over-exposure).
I haven't seen it in KITTI. 

However, there was a previous issue. I think it might be related.
It was related to the PyTorch version. 

Please check the issue below and try the solution.
https://github.com/Huangying-Zhan/DF-VO/issues/13#issuecomment-702014660

Let me know if it works.

**Comment by songwenhuang** [comment]
The issue was fixed after modifying "align_corners = True." Thanks.
