### ISSUE TITLE
start whit frame

### ISSUE THREAD

**Issue by chaoxingxi** [Huangying-Zhan/DF-VO#26]
When i run "python apis/run.py -d options/examples/default_configuration.yml"

Just appear below, how i select the start whit frame?
 
Save result in result/tmp/0/? [y/n]y
==> Initialize LiteFlowNet with [model_zoo/optical_flow/LiteFlowNet/network-default.pytorch]: 
==> Initialize Depth-CNN with [model_zoo/depth/kitti_odom/stereo/]
==> Start DF-VO
==> Running sequence: 10
Start with frame: 0
0it [00:00, ?it/s]
=> Finish!
The result is saved in [result/tmp/0/].
Save VO map.
Trajectory saved.
----- time breakdown -----
Group [single]:

**Comment by Huangying-Zhan** [comment]
It starts with frame-0 (by default). The reason that option is there is for debugging purpose, in case you want to start from the middle of a video.

And it seems to me that your data directory is not provided correctly so no images are loaded.

**Comment by chaoxingxi** [comment]
Thank you
my dataset images type is .png 
so, set "ext: png" in default_configuration.yml is OK
