### ISSUE TITLE
The datasets/kitti.py of this code is not available ？

### ISSUE THREAD

**Issue by yangbinchao** [Huangying-Zhan/DF-VO#27]
Thank you for your excellent work and sharing. When I was about to run this code, the datasets/kitti.py of this code was not available.
![截屏2021-06-29 下午9 57 41](https://user-images.githubusercontent.com/47782077/123810512-0a043f80-d925-11eb-93b3-572d3d4425ab.png)
thank you for your reply.

**Comment by Huangying-Zhan** [comment]
The available datasets are provided here.
https://github.com/Huangying-Zhan/DF-VO/blob/6a2ec43fc6209d9058ae1709d779c5ada68a31f3/libs/datasets/__init__.py#L7
