### ISSUE TITLE
output problem

### ISSUE THREAD

**Issue by xhangHU** [Huangying-Zhan/DF-VO#31]
Save result in result/tmp/0/? [y/n]y
==> Initialize LiteFlowNet with [model_zoo/optical_flow/LiteFlowNet/network-default.pytorch]:
==> Initialize Depth-CNN with [model_zoo/depth/kitti_odom/stereo/]
==> Start DF-VO
==> Running sequence: 10
Start with frame: 0
0it [00:00, ?it/s]
=> Finish!
The result is saved in [result/tmp/0/].
Save VO map.
Trajectory saved.

**Comment by belkahorry** [comment]
> Cannot find enough good keypoints from diversed regions! No enough good keypoints, constant motion will be used! 0%|▏ | 1/1201 [00:00<11:49, 1.69it/s] Traceback (most recent call last): File "run.py", line 85, in vo.main() File "/root/docker2/DFVO/DF-VO/libs/dfvo.py", line 378, in main self.tracking() File "/root/docker2/DFVO/DF-VO/libs/dfvo.py", line 158, in tracking pose = self.ref_data['motion'] KeyError: 'motion' Can you help me！

Hi,Have you got any solutions to this?
Thanks

**Comment by Huangying-Zhan** [comment]
Hi all,
The problem has been fixed. Please see the updated code in `dfvo.py` line 134.

**Comment by oxyhexagen** [comment]
> Hi all, The problem has been fixed. Please see the updated code in `dfvo.py` line 134.

Much appreciate for your reply! 
I have solved this problem by adding 'align_corners = True' ,mentioned in #13

**Comment by Tian0906** [comment]
> > 大家好，问题已经解决。请参阅第 134 行更新后的代码`dfvo.py`。
> 
> 非常感谢您的回复！ 我通过添加[#13中提到的 'align_corners = True' 解决了这个问题](https://github.com/Huangying-Zhan/DF-VO/issues/13)

Hi, can you tell me exactly where in the program the "align_corners" flag needs to be changed? Thank you very much!
