### ISSUE TITLE
The expected results are unavailable.

### ISSUE THREAD

**Issue by Jierui-Liu** [Huangying-Zhan/DF-VO#34]
Hi, thanks for your excellent works and sharing. I can't get the expected results with the code. 
When I execute the command: 
python run.py -d options\kitti\kitti_default_configuration.yml
The result I get is like that:
![image](https://user-images.githubusercontent.com/61498320/159113001-dc15e0a0-6fc3-421d-9abd-ad6898f487a4.png)
The final saved result is as follows:
![image](https://user-images.githubusercontent.com/61498320/159113031-b2699ba8-550c-44b5-8496-cb8e3fc9e0a1.png)
The predicted trajectory is much different from the ground truth, and even the ground truth is visualized incomplete.

Only the image.ext in the kitti_default_configuration.yml is changed from 'jpg'  to 'png', because the images in KITTI2012 are with png form. Nothing else in the code is changed.

Thank your for your help.

**Comment by Jierui-Liu** [comment]
Besides, there are many warnings about "no enough good keypoints" during running as follows:
![image](https://user-images.githubusercontent.com/61498320/159113983-92b5e3fc-1f37-4b40-a86d-c8f0ae4e264a.png)

**Comment by oxyhexagen** [comment]
If your torch version is beyond 1.2.0 , perhaps you should alter the flag 'align_corners',mentioned in #13

**Comment by Jierui-Liu** [comment]
> If your torch version is beyond 1.2.0 , perhaps you should alter the flag 'align_corners',mentioned in #13

Thanks！It works.

**Comment by Jierui-Liu** [comment]
> If your torch version is beyond 1.2.0 , perhaps you should alter the flag 'align_corners',mentioned in #13

@belkahorry Thanks！It works.

**Comment by Tian0906** [comment]
> [如果您的火炬版本超过 1.2.0 ，也许您应该更改#13](https://github.com/Huangying-Zhan/DF-VO/issues/13)中提到的标志“align_corners”[](https://github.com/Huangying-Zhan/DF-VO/issues/13)

Hi, can you tell me exactly where in the program the "align_corners" flag needs to be changed?Thank you very much!

**Comment by Jierui-Liu** [comment]
Please see the function "Backward" at the begining of the file "DF-VO/libs/deep_models/flow/lite_flow_net/lite_flow_net.py at master · Huangying-Zhan/DF-VO · GitHub".
Its output should be modified as "return torch.nn.functional.grid_sample(input=tensorInput, grid=(Backward_tensorGrid[str(tensorFlow.size())] + tensorFlow).permute(0, 2, 3, 1), mode='bilinear', padding_mode='zeros',align_corners = True)"


I&nbsp;AM
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Huangying-Zhan/DF-VO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月25日(星期天) 下午3:56
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Huangying-Zhan/DF-VO] The expected results are unavailable. (Issue #34)





  
如果您的火炬版本超过 1.2.0 ，也许您应该更改#13中提到的标志“align_corners”
  
Hi, can you tell me exactly where in the program the "align_corners" flag needs to be changed?Thank you very much!

**Comment by Tian0906** [comment]
> 请参阅“Master·Huangying-Zhan/DF-VO·GitHub”文件“DF-VO/libs/deep_models/flow/lite_flow_net/lite_flow_net.py at master·Huangying-Zhan/DF-VO·GitHub”开头的“Backward”函数。其输出应修改为“return torch.nn.function.grid_sample(input=tensorInput, grid=(Backward_tensorGrid[str(tensorFlow.size())] + tensorFlow).permute(0, 2, 3, 1), mode ='双线性', padding_mode='零',align_corners = True)" 我是 ***@***.***  
> [……](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Huangying-Zhan/DF-VO" ***@***.***&gt;; 发送时间:&nbsp;2023年6月25日(星期天) 下午3:56 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [Huangying-Zhan/DF-VO] The expected results are unavailable. (Issue #34) 如果您的火炬版本超过 1.2.0 ，也许您应该更改#13中提到的标志“align_corners” Hi, can you tell me exactly where in the program the "align_corners" flag needs to be changed?Thank you very much! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

The problem is solved, thank you very much!
