### ISSUE TITLE
Training the model with new data

### ISSUE THREAD

**Issue by jordigc2** [Huangying-Zhan/DF-VO#35]
Hello,

Is there any progress or guide on how to retrain the model with new datasets?
I have seen that there was already an issue [#4] where @Huangying-Zhan said he didn't have in mind to publish how to retrain it. But did anyone succeeded or found how to do it?

Thank you.

**Comment by Huangying-Zhan** [comment]
Hi @jordigc2 , I didn't get a chance to release the training framework but I have already released the code that we used for online fine-tuning (optical flow).
The training code is basically as same as the one we proposed in the paper.

For depth model training, please refer to monodepth2 and sc-sfmlearner.

Please see here: https://github.com/Huangying-Zhan/DF-VO/blob/master/libs/deep_models/flow/deep_flow.py
I believe you can simply reuse the code for training optical flow model.

**Comment by jordigc2** [comment]
Hi @Huangying-Zhan ,
Thanks for your prompt replay. 
Both Nets are trained simultaneously right? At least is the idea I got from the paper chapter 4.6 (Jointly learning of depths and pose). 
I assume I need to get inspired by the two references you shared to build the simultaneously training framework right?

**Comment by Huangying-Zhan** [comment]
Hi @jordigc2 , 
Yes, for the depth and pose networks, you can refer to the two references I mentioned above.
The training of these two networks is based on the two references.

**Comment by jordigc2** [comment]
Hi @Huangying-Zhan ,
Thank you very much. When reading the paper I first understood that it was training the DepthNet and the FlowNet simultaneously, as it's done in TrainFlow(https://github.com/B1ueber2y/TrianFlow). 
But after checking the references I could see that the DepthNet + PoseNet is trained using monodepht2 and FlowNet using LiteFlowNet independently from each other and joint together for the inference.

Can you confirm me this is right?
I appreciate your time replying this messages.

**Comment by Huangying-Zhan** [comment]
you are right.
