### ISSUE TITLE
cupy has no attribute 'util' error

### ISSUE THREAD

**Issue by ggonzalez2022** [Huangying-Zhan/DF-VO#40]
/DF-VO-master/libs/deep_models/flow/lite_flow_net/correlation.py", line 276, in <module>
    @cupy.util.memoize(for_each_device=True)
AttributeError: module 'cupy' has no attribute 'util'

could someone please help me here ?

**Comment by 110sha** [comment]
@ggonzalez2022 Has this problem been resolved?
