### ISSUE TITLE
6DoF and 7DoF, what's the difference ?

### ISSUE THREAD

**Issue by IaroslavS** [Huangying-Zhan/DF-VO#6]
HI !
I can't find anywhere, what's the difference between 6DoF and 7DoF. Could you please tell me, what's the difference or give me link to the description ?

**Comment by Huangying-Zhan** [comment]
hi @IaroslavS , sorry for late reply. I was on leave previously.
6DoF: translation and rotation
7DoF: scale+6DoF

https://github.com/Huangying-Zhan/DF-VO/wiki/eval_odom

**Comment by IaroslavS** [comment]
> hi @IaroslavS , sorry for late reply. I was on leave previously.
> 6DoF: translation and rotation
> 7DoF: scale+6DoF
> 
> https://github.com/Huangying-Zhan/DF-VO/wiki/eval_odom

Thanks !
