### ISSUE TITLE
Half_flow

### ISSUE THREAD

**Issue by ShrutheeshIR** [Huangying-Zhan/DF-VO#7]
For 'network-default.pytorch' weights, why are the flows divided by 2. I tried going through liteflownet and could not find any such computation. What is the reason for halving the output of the optical flow

**Comment by Huangying-Zhan** [comment]
Hi @ShrutheeshIR , for liteflownet-default, I was using the reimplemented model provided by 
https://github.com/sniklaus/pytorch-liteflownet

When I was using this model, I found that I need to do this "half-flow" operation in order to get correct flow prediction. You can double check and let me know if there is any question.

**Comment by ShrutheeshIR** [comment]
Hey, thanks!
There was another query that I had. In the deep_flow_forward() function, I noticed that the reference key points are assigned to current frame and current keypoints are assigned to the ref_data. Is this done on purpose? If so, why is that?

**Comment by Huangying-Zhan** [comment]
Hi @ShrutheeshIR , yes, the code was written on purpose previously.

I think you are refering to this section.
https://github.com/Huangying-Zhan/DF-VO/blob/2590168dda0c2dad4ab9d30c831f723d6cf85865/vo_modules.py#L710

However it is not necessary for this version.

The previous reason is about an experiment I conducted, which is not just two-frame tracking, but multi-frames.
suppose we have 3 frames: f1, f2, f3.
f2 is my cur_frame while f1 and f3 are the reference.
Flows for (f1->f2) and (f3->f2) are computed.
the kp on f1 and f3 are the same, on the regular grid
the kp on f2 are different w.r.t f1 and f3. 
Therefore, I saved kp on both f1 and f3 (identical) on cur_data while kp got from (f1->f2) and (f3->f2) on ref_data. 
However, you can change the names and the related parts if it confused you.

**Comment by Huangying-Zhan** [comment]
Hi @ShrutheeshIR , yes, the code was written on purpose previously.

I think you are refering to this section.
https://github.com/Huangying-Zhan/DF-VO/blob/2590168dda0c2dad4ab9d30c831f723d6cf85865/vo_modules.py#L710

However it is not necessary for this version.

The previous reason is about an experiment I conducted, which is not just two-frame tracking, but multi-frames.
suppose we have 3 frames: f1, f2, f3.
f2 is my cur_frame while f1 and f3 are the reference.
Flows for (f1->f2) and (f3->f2) are computed.
the kp on f1 and f3 are the same, on the regular grid
the kp on f2 are different w.r.t f1 and f3. 
Therefore, I saved kp on both f1 and f3 (identical) on cur_data while kp got from (f1->f2) and (f3->f2) on ref_data. 
However, you can change the names and the related parts if it confused you.

**Comment by Huangying-Zhan** [comment]
re-open if need
